listFiles = dir('../atas');
corpus = "";
for i = 3:length(listFiles)
    str = fileread([listFiles(i).folder '\' listFiles(i).name]);
    corpus = strcat(corpus, ' ', str); %#ok<AGROW>
end

Mystopwords = {'de','a','em','e','o','do','da','no','para','que','com','se', ...
    'os','as','dos','na','ao','das','p','1','por','pelo','relação','mês',...
    'nas','sobre','pela','até','à','nos','um','como','não','entre','mesmo', ...
    'seu','seus','sua','suas','é','está','às','aos','10','após','também',...
    'esse','esses','essa','essas','isso','este','estes','esta','estas','isto',...
    'desse','desses','dessa','dessas','disso','deste','destes','desta','destas','disto',...
    'nesse','nesses','nessa','nessas','nisso','neste','nestes','nesta','nestas','nisto',...
    'aquele','aqueles','aquela','aquelas','aquilo', 'àquela','àquelas', ...
    'naquele','naqueles','naquela','naquelas','naquilo', ...
    'daquele','daqueles','daquela','daquelas','daquilo', ...
    '0%','1%','2%','3%','4%','5%','6%','7%','8%','9%','uma','desde',...
    'janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', ...
    'agosto', 'setembro', 'outubro', 'novembro', 'dezembro', 'mês', 'meses', ... 
    'ano', 'anos', 'ainda', 'ante', 'p','r' ...
    'com', 'dela', 'delas', 'dele', 'deles', 'depois', 'era', 'eram', 'éramos', ... 
    'essa', 'essas', 'esse', 'esses', 'esta', 'está', 'estamos', 'estão', ...
    'estar', 'estas', 'estava', 'estavam', 'estávamos', 'este', 'esteja', ...
    'estejam', 'estejamos', 'estes', 'esteve', 'estive', 'estivemos', ...
    'estiver', 'estivera', 'estiveram', 'estivéramos', 'estiverem', ...
    'estivermos', 'estivesse', 'estivessem', 'estivéssemos', 'estou', ...
    'eu', 'foi', 'fomos', 'for', 'fora', 'foram', 'fôramos', 'forem', ...
    'formos', 'fosse', 'fossem', 'fôssemos', 'fui', 'há', 'haja', ...
    'hajam', 'hajamos', 'hão', 'havemos', 'haver', 'hei', 'houve', ...
    'houvemos', 'houver', 'houvera', 'houverá', 'houveram', 'houvéramos', ...
    'houverão', 'houverei', 'houverem', 'houveremos', 'houveria', 'houveriam', ...
    'houveríamos', 'houvermos', 'houvesse', 'houvessem', 'houvéssemos', ... 
    'já', 'lhe', 'lhes', 'mais', 'mas', 'me', 'mesmo', 'meu', 'meus', 'minha', ...
    'minhas', 'muito', 'na', 'não', 'nas', 'nem', 'no', 'nos', 'nós', 'nossa', ...
    'nossas', 'nosso', 'nossos', 'num', 'numa', 'ou', 'pelas', 'pelos', 'qual', ...
    'quando', 'quem', 'são', 'se', 'seja', 'sejam', 'sejamos', 'sem', 'ser', ... 
    'será', 'serão', 'serei', 'seremos', 'seria', 'seriam', 'seríamos', ...
    'seu', 'seus', 'só', 'somos', 'sou', 'sua', 'suas', 'também', 'te', ...
    'tem', 'tém', 'temos', 'tenha', 'tenham', 'tenhamos', 'tenho', 'terá', ...
    'terão', 'terei', 'teremos', 'teria', 'teriam', 'teríamos', 'teu', 'teus', ...
    'teve', 'tinha', 'tinham', 'tínhamos', 'tive', 'tivemos', 'tiver', 'tivera', ...
    'tiveram', 'tivéramos', 'tiverem', 'tivermos', 'tivesse', 'tivessem', ...
    'tivéssemos', 'tu', 'tua', 'tuas', 'um', 'uma', 'você', 'vocês', 'vos', ...
    '0','1','2','3','4','5','6','7','8','9'};
NRWORDS=20;

disp('WORD FREQUENCY WITH STOP WORDS')
[result, count] = wordFrequency(corpus, NRWORDS, {});
disp('')
disp('WORD FREQUENCY WITHOUT STOP WORDS')
[result2, count2] = wordFrequency(corpus, NRWORDS, Mystopwords);

function [result,count] = wordFrequency(text, nrWords, stopwords)
% Adapted from:
% https://rosettacode.org/wiki/Word_frequency#MATLAB_/_Octave
    WITHSTOPWORDS = boolean(length(stopwords));
    DELIMITER={' ', ',', ';', ':', '.', '/', '*', '!', '?', '<', '>', '(', ')', '[', ']','{', '}', '&','$','§','"','”','“','-','—','‘','\t','\n','\r'};
    words  = sort(strsplit(lower(text),DELIMITER));
    flag   = [find(~strcmp(words(1:end-1),words(2:end))),length(words)];
    dwords = words(flag);   % get distinct words, and ...
    count  = diff([0,flag]);  % ... the corresponding occurance frequency
    [~,idx] = sort(-count);       % sort according to occurance
    result = dwords(idx);
    count  = count(idx);
    c = 1;
    k = 1;
    while c <= nrWords && k < length(result)
        if WITHSTOPWORDS
        indx = find(strcmp(stopwords, result{k}), 1);
        if isempty(indx)
            fprintf(1,'%d\t%s\n',count(k),result{k})
            c = c + 1;
        end
        k = k + 1;
        else
            fprintf(1,'%d\t%s\n',count(k),result{k})
            c = c + 1;
            k = k + 1;
        end
    end
end
 